CREATE TABLE TBL_PROJECT (
    ID INT PRIMARY KEY IDENTITY(1,1),
	PRO_MASTER_ID INT,
	IS_ACTIVE INT,
    PROJECT_NAME VARCHAR(150),
	SPOC VARCHAR(50),
	IBL_PRIORITY INT,
	CURRENT_PHASE VARCHAR(150),
	STATUS VARCHAR(150),
	NEXT_PHASE VARCHAR(150),
	CR_DETAILS VARCHAR(MAX),
    RAG_STATUS VARCHAR(150),
    CURRRENT_PROGRESS VARCHAR(MAX),
	DEV_START VARCHAR(50),
	UAT_RELEASE VARCHAR(50),
	UAT_SIGNOFF VARCHAR(50),
	PREPROD_RELEASE VARCHAR(50),
	PREPROD_SIGNOFF VARCHAR(50),
	PROD_RELEASE VARCHAR(50),
    CREATED_ON VARCHAR(50),
	CREATED_BY INT,
	MODIFIED_ON VARCHAR(50),
	MODIFIED_BY INT
);


CREATE TABLE TBL_PROJECT_MASTER (
    ID INT PRIMARY KEY IDENTITY(1,1),
    PROJECT VARCHAR(100),
	ENVIRONMENT VARCHAR(50)
);
INSERT INTO TBL_PROJECT_MASTER(PROJECT,ENVIRONMENT)
VALUES ('EASY PL','DevUatPreProd');
INSERT INTO TBL_PROJECT_MASTER(PROJECT,ENVIRONMENT)
VALUES ('LOP','DevUatPreProd');
INSERT INTO TBL_PROJECT_MASTER(PROJECT,ENVIRONMENT)
VALUES ('EMI DC','UatPreProd');

CREATE TABLE TBL_USER (
    ID INT PRIMARY KEY IDENTITY(1,1),
    USER_NAME VARCHAR(150),
	PASSWORD VARCHAR(50)
);
INSERT INTO TBL_USER(USER_NAME,PASSWORD)
VALUES ('admin','admin');